version: '3'
services:
  mpc:
    depends_on:
      - db
    ports:
      - 3000:3000
    image: mpc
    build: .
    environment:
      DATABASE_URL: postgres://mpc:password@db:5432/mpc
  db:
    ports:
      - 5432:5432
    image: postgres:alpine
    environment:
      POSTGRES_USER: mpc
      POSTGRES_PASSWORD: password
  client:
    image: mpc
    command: node client.js
    environment:
      API_URL: https://mpc.cosset.cf
  client-init:
    image: mpc
    command: node ./client/cosset.init.js
    environment:
      COSSET_API_URL: https://wallet.cosset.cf
  client-sign:
    image: mpc
    command: node ./client/cosset.sign.js
    environment:
      COSSET_API_URL: https://wallet.cosset.cf
      COSSET_CRYPTO_URL: https://crypto.cosset.cf

  client-init-ed25519:
    image: mpc
    command: node ./client/cosset.init.ed25519.js
    environment:
      COSSET_API_URL: https://wallet.cosset.cf

  client-sign-algo:
    image: mpc
    command: node ./client/cosset.sign.algo.js
    environment:
      COSSET_API_URL: https://wallet.cosset.cf
      COSSET_CRYPTO_URL: http://docker.for.mac.host.internal:3001

  client-sign-bitcoin:
    image: mpc
    command: node ./client/cosset.sign.bitcoin.js
    environment:
      COSSET_API_URL: https://wallet.cosset.cf
      COSSET_CRYPTO_URL: http://docker.for.mac.host.internal:3001

  client-compound-deposit:
    image: mpc
    command: node ./client/cosset.compound.deposit.js
    environment:
      COSSET_API_URL: https://wallet.cosset.cf
      COSSET_CRYPTO_URL: https://crypto.cosset.cf

  client-compound-withdraw:
    image: mpc
    command: node ./client/cosset.compound.withdraw.js
    environment:
      COSSET_API_URL: https://wallet.cosset.cf
      COSSET_CRYPTO_URL: https://crypto.cosset.cf
